import type { MLDTable, SqlDialect } from '~/types'

const TYPE_MAP: Record<SqlDialect, Record<string, string>> = {
  postgresql: { AUTOINCREMENT: 'SERIAL', INT: 'INTEGER', BIGINT: 'BIGINT', VARCHAR: 'VARCHAR(255)', TEXT: 'TEXT', DATE: 'DATE', BOOLEAN: 'BOOLEAN', FLOAT: 'FLOAT', DECIMAL: 'DECIMAL(10,2)', UUID: 'UUID' },
  mysql:      { AUTOINCREMENT: 'INT AUTO_INCREMENT', INT: 'INT', BIGINT: 'BIGINT', VARCHAR: 'VARCHAR(255)', TEXT: 'TEXT', DATE: 'DATE', BOOLEAN: 'TINYINT(1)', FLOAT: 'FLOAT', DECIMAL: 'DECIMAL(10,2)', UUID: 'CHAR(36)' },
  sqlite:     { AUTOINCREMENT: 'INTEGER', INT: 'INTEGER', BIGINT: 'INTEGER', VARCHAR: 'TEXT', TEXT: 'TEXT', DATE: 'TEXT', BOOLEAN: 'INTEGER', FLOAT: 'REAL', DECIMAL: 'REAL', UUID: 'TEXT' },
}

export function generateSQL(tables: MLDTable[], dialect: SqlDialect): string {
  const map = TYPE_MAP[dialect]
  const lines: string[] = [`-- Generated by Open Data Modeler (${dialect.toUpperCase()})\n`]

  tables.forEach(table => {
    const cols: string[] = []
    const pks: string[]  = []
    const fks: string[]  = []

    table.columns.forEach(col => {
      const sqlType = map[col.type] ?? col.type
      const isAI = col.type === 'AUTOINCREMENT'

      if (dialect === 'sqlite' && isAI && col.isPrimary) {
        cols.push(`  ${col.name} INTEGER PRIMARY KEY AUTOINCREMENT`)
        return
      }
      cols.push(`  ${col.name} ${sqlType}${col.isPrimary && !isAI ? ' NOT NULL' : ''}`)
      if (col.isPrimary && !isAI) pks.push(col.name)
      if (col.fk && col.fkRef) fks.push(`  FOREIGN KEY (${col.name}) REFERENCES ${col.fkRef}(${col.name.replace(`_${col.fkRef.toLowerCase()}`, '')})`)
    })

    if (pks.length > 0) cols.push(`  PRIMARY KEY (${pks.join(', ')})`)
    cols.push(...fks)

    lines.push(`CREATE TABLE IF NOT EXISTS ${table.name} (\n${cols.join(',\n')}\n);\n`)
  })

  return lines.join('\n')
}
